### Stop Words

In [2]:
import spacy

from spacy.lang.en.stop_words import STOP_WORDS

print(STOP_WORDS)
len(STOP_WORDS)

{'this', 'any', 'yours', 'below', 'if', 'became', '‘m', 'latterly', 'has', 'and', 'its', 'or', 'everyone', 'however', 'move', 'others', '’d', 'each', 'nine', 'down', 'keep', 'during', 'through', 'when', 'twelve', 'most', 'although', 'do', 'as', 'before', "'m", 'hundred', 'there', 'seemed', 'with', 'yourselves', 'see', 'is', 'often', 'anyone', 'quite', 'no', 'moreover', 'except', 'put', 'though', 'latter', 'a', 'n’t', 'whereupon', 'regarding', 'sometime', 'unless', 'nor', 'her', 'him', 'by', 'either', 'something', 'too', 'used', 'afterwards', 'while', 'further', '‘ve', 'how', 'hereafter', 'show', '‘d', 'myself', 'ten', 'once', 'yourself', 'just', 'towards', 'some', '’ll', 'other', 'you', 'not', 'very', '’s', 'three', 'thence', 'say', 'why', 'us', 'less', 'doing', 'against', 'thereby', 'since', 'four', 'itself', 'every', 'throughout', 'whose', "'re", 'himself', 'noone', 'such', 'whether', 'an', 'will', 'being', 'many', 'really', 'eight', 'whenever', 'across', 'up', 'least', 'again', 'between', 'could', 'it', 'herself', 'next', 'side', 'of', 'several', 'anyhow', 'sometimes', 'be', 'due', 'take', 'both', 'so', 'me', 'whereas', 'fifteen', 'somehow', 'their', 'for', 'who', 'still', 'behind', 'themselves', 'one', "'d", 'somewhere', 'same', 'beside', 'after', 'whereafter', 'beforehand', 'thus', 'your', 'first', 'sixty', 'ours', 'my', 'does', 'part', "n't", 'anyway', 'go', 'should', 'can', 'we', 'these', 'because', 'those', 'at', 'above', 'here', 'among', 'ourselves', 'someone', 'about', 'front', 'rather', 'otherwise', 'upon', 'get', 'nevertheless', '’ve', 'off', 'therefore', 'thru', 'eleven', 'to', 'call', "'s", 'am', 'did', 'nothing', 'two', 'via', 'which', 'few', 'all', 'along', 'various', 'he', 'wherever', 'only', '‘ll', 'fifty', 'hereupon', 'amongst', 'until', 'five', 'under', 'per', 'twenty', 'please', 'whither', 'been', 'herein', 'becoming', "'ll", 'full', 'that', 'elsewhere', 'seem', 'third', 'perhaps', 'give', 'seems', 'she', 'top', 'on', 'than', 'already', 'make', 'serious', 'was', 'whatever', 'might', 'six', 'namely', 'where', 'bottom', 'were', 'onto', 'alone', 'they', 'beyond', 'yet', 'whereby', 'everywhere', 'what', 'ever', "'ve", 'indeed', 'over', '‘s', 'never', 'then', 'nowhere', 'anywhere', 'back', 'everything', 'together', 'toward', 'become', 'well', 'wherein', 'else', 'using', 'are', 'thereupon', 'hence', 'anything', 'would', 'around', 'within', 'nobody', 'always', 'in', 'n‘t', 'becomes', 'neither', 'done', 'hereby', 'into', 'amount', 'now', 'cannot', 'hers', '’re', 're', 'whence', 'former', 'the', 'therein', 'our', 'them', 'meanwhile', 'but', 'have', 'made', 'mostly', 'whom', 'formerly', 'ca', 'empty', 'forty', 'last', 'another', 'enough', 'his', 'thereafter', 'much', 'whole', 'besides', 'may', 'seeming', 'more', 'from', '‘re', 'none', 'must', 'also', 'name', 'out', '’m', 'had', 'even', 'without', 'almost', 'mine', 'whoever', 'i', 'own'}

326

In [3]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("I am Sakshi and I am learning Natural Language Processing")

for token in doc:
    if token.is_stop:
        print(token)

I
am
and
I
am

In [4]:
def preprocess(text):
    doc = nlp(text)

    no_stop_words = [token.text for token in doc if not token.is_stop and not token.is_punct]
    return " ".join(no_stop_words)

preprocess("I am Sakshi and I am learning Natural Language Processing, I love to work with the AI/ML.")

'Sakshi learning Natural Language Processing love work AI ML'

In [5]:
import pandas as pd

df = pd.read_json("doj_press.json", lines=True)

df.shape

(13087, 6)

In [6]:
df.head()

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [7]:
df = df[df["topics"].str.len() != 0]

df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [8]:
df = df.head(100)
df.shape

(100, 6)

In [9]:
len(df["contents"].iloc[4])

5504

In [10]:
df["contents_new"] = df["contents"].apply(preprocess)

df.head()

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],U.S. Department Justice U.S. Environmental Pro...
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],131 count criminal indictment unsealed today B...
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...",United States Attorney Office Middle District ...
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],21st Century Oncology LLC agreed pay $ 19.75 m...
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]",21st Century Oncology Inc. certain subsidiarie...

In [11]:
len(df["contents_new"].iloc[4])

4217

In [12]:
len(df["contents"].iloc[4])

5504

In [13]:
df["contents"].iloc[4][:300]

'21st Century Oncology Inc. and certain of its subsidiaries and affiliates have agreed to pay $26 million to the government to resolve a self-disclosure relating to the submission of false attestations regarding the company’s use of electronic health records software and separate allegations that the'

In [14]:
df["contents_new"].iloc[4][:300]

'21st Century Oncology Inc. certain subsidiaries affiliates agreed pay $ 26 million government resolve self disclosure relating submission false attestations company use electronic health records software separate allegations violated False Claims Act submitting causing submission claims certain serv'

### Exercise Questions

#### Exercise 1
<ul> 
<li>From a Given Text, Count the number of stop words in it.</li>
<li>Print the percentage of stop word tokens compared to all tokens in a given text.</li>
</ul>

In [22]:
text = '''
Thor: Love and Thunder is a 2022 American superhero film based on Marvel Comics featuring the character Thor, produced by Marvel Studios and 
distributed by Walt Disney Studios Motion Pictures. It is the sequel to Thor: Ragnarok (2017) and the 29th film in the Marvel Cinematic Universe (MCU).
The film is directed by Taika Waititi, who co-wrote the script with Jennifer Kaytin Robinson, and stars Chris Hemsworth as Thor alongside Christian Bale, Tessa Thompson,
Jaimie Alexander, Waititi, Russell Crowe, and Natalie Portman. In the film, Thor attempts to find inner peace, but must return to action and recruit Valkyrie (Thompson),
Korg (Waititi), and Jane Foster (Portman)—who is now the Mighty Thor—to stop Gorr the God Butcher (Bale) from eliminating all gods.
'''

doc = nlp(text)

stopWordsText = []
stopWords = 0
wordsCount = 0

for token in doc:
    if token.is_stop:
        stopWords += 1
    wordsCount += 1

print("Total stop words count: ",stopWords)
print("Total words count: ", wordsCount)

print("Percentage of stop words: ", stopWords / wordsCount * 100)

Total stop words count:  40
Total words count:  160
Percentage of stop words:  25.0

#### Exercise 2

<ul>
<li>Spacy default implementation considers "not" as a stop word. But in some scenarios removing 'not' will completely change the meaning of the statement/text. For Example, consider these two statements:

- this is a good movie       ----> Positive Statement
- this is not a good movie   ----> Negative Statement</li>
<li>So, after applying stopwords to those 2 texts, both will return "good movie" and does not respect the polarity/sentiments of text.</li>

<li>Now, your task is to remove this stop word "not" in spaCy and help in distinguishing the texts.</li>
</ul>

In [ ]:
def preprocess(text):
    doc = nlp(text)
    no_Stop_words = [token.text for token in doc if not token.is_stop]
    return " ".join(no_Stop_words)

# 1. Remove stop words from the text
nlp.vocab['not'].is_stop = False


positive_text = preprocess("this is a good movie")
negative_text = preprocess("this is not a good movie")

print(f"Text1: {positive_text}")
print(f"Text2: {negative_text}")

Text1: good movie
Text2: not bad movie


#### Exercise3:

From a given text, output the most frequently used token after removing all the stop word tokens and punctuations in it.

In [29]:
text = ''' The India men's national cricket team, also known as Team India or the Men in Blue, represents India in men's international cricket.
It is governed by the Board of Control for Cricket in India (BCCI), and is a Full Member of the International Cricket Council (ICC) with Test,
One Day International (ODI) and Twenty20 International (T20I) status. Cricket was introduced to India by British sailors in the 18th century, and the 
first cricket club was established in 1792. India's national cricket team played its first Test match on 25 June 1932 at Lord's, becoming the sixth team to be
granted test cricket status.
'''

doc = nlp(text)

remaining_tokens = []

for token in doc:
    if token.is_stop or token.is_punct:
        continue
    remaining_tokens.append(token.text)

frequency = {}

for token in remaining_tokens:
    if token != '\n' and token != ' ':
        if token not in frequency:
            frequency[token] = 1
        else:
            frequency[token] += 1    

max_freq_word = max(frequency.keys(), key = (lambda key: frequency[key]))         

print("Most frequent word: ", max_freq_word)

Most frequent word:  India